### ISSUE TITLE
syntax error near unexpected token `-1'

### ISSUE THREAD

**Issue by thevenomsnake** [acbetter/cqut_student_schedule_py#1]
syntax error near unexpected token `-1'.
How to slove it ? (´▽`ʃ♡ƪ)

**Comment by acbetter** [comment]
@thevenomsnake The command should be `python3 cuqt.py -u 11501230123 -p abcd3456`. If your password had char like  `, you need to change your command to 
```
python3 cuqt.py -u 11501230123 -p 'abcd`3456'
```
